### ISSUE TITLE
Touchscreen working for you?

### ISSUE THREAD

**Issue by jamespfarrell** [rolandguelle/razer-blade-stealth-linux#1]
Hey Roland,

Thanks for your great page here:
https://github.com/rolandguelle/razer-blade-stealth-linux

It has helped me quite a lot.

I was wondering if your touch screen is working for your Razer Blade Stealth?

I have installed Ubuntu 17.04 Gnome, and it's not working for me....

Thanks
James

**Comment by rolandguelle** [comment]
Thanks for your feedback!
The touch screen is working fine, my Ubuntu 17.04 installation is no fresh installation, it is an 16.10 update.
My Ubuntu installation uses X, libinput and Unity.
The Arch Linux installation uses Wayland and Gnome, without any issues with the touch screen.

What is your `xinput list` output? Does it contains the "ELAN Touchscreen"?
Does `libinput-debug-events` return events when touching the screen?

**Comment by jamespfarrell** [comment]
I finally realised that the touchscreen is actually working, it was only Firefox, which was the only thing I had installed that wasn't working.

Thanks for taking the time to reply to me though :)
