### ISSUE TITLE
Caps Lock probably fixed in Ubuntu 17.10.1

### ISSUE THREAD

**Issue by lucaszanella** [rolandguelle/razer-blade-stealth-linux#11]
Installed it days ago and didn't have the problem at all, and didn't apply any of the fixes here. Maybe worth putting this information on the Caps Lock issue

**Comment by rolandguelle** [comment]
Thanks for test and feedback!
Currently I use Wayland, and I (only) use the /etc/default/keyboard fix:
https://github.com/rolandguelle/razer-blade-stealth-linux#disable-capslocks
without the X11 fix.

I removed the fix - and the system hangup on login screen (gdm).
I'll add a comment about Wayland & X11.

**Comment by rolandguelle** [comment]
https://github.com/rolandguelle/razer-blade-stealth-linux/commit/b4f5d6281b18ff23a301a5f94af19e1546be3fd3

**Comment by lucaszanella** [comment]
Which Ubuntu you're using? Perhaps the new kernel fixes it? Because I had no problem at all

**Comment by lucaszanella** [comment]
Did a microcode update and the problem returned. Don't know what to say, shouldn't be related...

**Comment by rolandguelle** [comment]
Thanks for retesting, lets keep this fix in the tutorial.
My Arch installation never has this problem. Seems to be a Ubuntu specific problem.
