### ISSUE TITLE
Document OpenRazer

### ISSUE THREAD

**Issue by wolfy1339** [rolandguelle/razer-blade-stealth-linux#13]
I found them when looking for an alternative to disabling my caps lock key in order to fix the bug with it.
They offer drivers for various razer peripherals

**Comment by rolandguelle** [comment]
I tried https://openrazer.github.io/, but I run into this bug:
https://github.com/openrazer/openrazer/issues/342

https://github.com/rolandguelle/razer-blade-stealth-linux/#keyboard-colors

**Comment by wolfy1339** [comment]
I personally have the Gunmetal, which doesn't have Chroma. I haven't hit that bug, as I don't really use the backlight

**Comment by wolfy1339** [comment]
I think it would also be good to add it for the Caps Lock bug too, since it does fix that

**Comment by rolandguelle** [comment]
Fix openrazer the caps lock bug?

**Comment by wolfy1339** [comment]
If you install openrazer's keyboard driver, it fixes the CAPS Lock bug.
________________________________

**Comment by rolandguelle** [comment]
Thanks for feedback!
I'm very sure I've tested this and it won't fix the bug, but I'll recheck this on my RBS.

**Comment by wolfy1339** [comment]
I installed it and it actually does fix that bug. There are other sources that state the same
________________________________

**Comment by rolandguelle** [comment]
Are you on Wayland or X?

**Comment by wolfy1339** [comment]
Not sure. I'm on the default one (must be Wayland)
________________________________

**Comment by rolandguelle** [comment]
Install openrazer won't fix the problem in my machine.

What I've done:
- I removed the fix (/etc/default/keyboard), reboot.
- Caps Lock crashes my machine (as expected)
- Install openrazer (and polychromatic), reboot
- While booting and on Login, Caps Lock crashes the system
- my profile is stable, but caps lock is still disabled
- New user with fresh profile (and working polychromatic) - system crashes
- The openrazer bug https://github.com/openrazer/openrazer/issues/342 keep the keyboard dark after suspend

**Comment by rolandguelle** [comment]
Tested with Wayland and X
