### ISSUE TITLE
Ubuntu 17.10 libinput instead of synaptics

### ISSUE THREAD

**Issue by fabiocarneiro** [rolandguelle/razer-blade-stealth-linux#14]
In the guide, there is an "X11" synaptic configuration for the touchpad, but apparently, 17.10 is using "libinput" (synclient wasn't even available). 

That makes the step useless unless there are additional instructions on how to replace libinput with synaptic.

**Comment by rolandguelle** [comment]
Thats true, if you use the Gnome/Wayland setup shipped with Ubuntu.
But with X11, the synaptics setup runs (in my option) better.

**Comment by fabiocarneiro** [comment]
Did you try both with X11 and Wayland? Do you recommend switching to X11 then?

If that is the case, maybe the instructions that could be included as a previous step to this "X11" step?

**Comment by rolandguelle** [comment]
Libinput only with Wayland, with X11 I run XFCE4 (and tried Budgie and others).

If you have issues with libinput, check the libinput tools:
https://wayland.freedesktop.org/libinput/doc/latest/tools.html
`libinput debug-events`

**Comment by fabiocarneiro** [comment]
I understand you have your customized settings and I'm not complaining about the guide in any way (I think its amazing that you did it) but don't you agree that ideally try to follow out of the box ubuntu settings or at least instruct what to customize?

**Comment by rolandguelle** [comment]
The guide is my settings, if you run Ubuntu & Wayland :)
I add the X11 settings only if you prefer X11.

I'll add that all X11 configurations are only needed, if you prefer X11 (I thought that this was clear).

**Comment by fabiocarneiro** [comment]
I tried also with X11 and those settings but I still see some weird behavior on the touchpad.

If I try to keep my finger on it and rotate, at some point it stops the cursor and I have to remove the finger and touch again for it to recognize input again. I'm wondering if this isn't a hardware issue as I have it only for one week and was using a mouse before.

**Comment by rolandguelle** [comment]
Confirmed the behavior on my machine with libinput / wayland.

**Comment by rolandguelle** [comment]
Note: I don't have to remove my finger. the cursor has a small delay or different acceleration.

**Comment by rolandguelle** [comment]
https://insider.razer.com/index.php?threads/ubuntu-17-10-blade-stealth-late-2017-issues.28967/

**Comment by rolandguelle** [comment]
The Arch setup with a 4.15.x kernel and a fresh libinput has not this issue (Gnome/Wayland/libinput)

**Comment by rolandguelle** [comment]
Arch Setup:
libinput 1.10.3 / kernel 4.15.15-1
https://github.com/rolandguelle/razer-blade-stealth-linux#libinput-coordinates

**Comment by rolandguelle** [comment]
Note: If I make lots of cycles on the touchpoint without changing the position, the cursor is moving around the screen on Arch (the bug is also there!).

**Comment by rolandguelle** [comment]
The "cycles without moving" tests seems to work on my XFCE4 / Arch setup (not in the tutorial) using the Synaptics driver.
TODO: Test Synaptics on Gnome & Ubuntu.

**Comment by rolandguelle** [comment]
[Libinput](https://insider.razer.com/index.php?threads/ubuntu-17-10-blade-stealth-late-2017-issues.28967/) is the problem.
The Synaptics Version with X11 has no tmp problems.

**Comment by fabiocarneiro** [comment]
> TODO: Test Synaptics on Gnome & Ubuntu.

Did you do that? Because with ubuntu + x11 I had problems too. The behavior seems to be different, but still not perfect.

Do you think it is possible to configure libinput or it would only work with synaptics?

**Comment by rolandguelle** [comment]
Yes, I've tested it. Ubuntu + X11 + Synaptics works fine. I still use libinput-gestures. The fresh libinput version on Arch is better, but still buggy in some cases.
I think X11 and Synaptics is not a bad choice:
Ubuntu 18.04 will switch back to X11 (from Wayland).

If you test it:
Could you check if installing xserver-xorg-input-synaptics is enough?

I've XFCE4 and Openbox installed...
