### ISSUE TITLE
Unable to change libinput-gesture config

### ISSUE THREAD

**Issue by ceiphr** [rolandguelle/razer-blade-stealth-linux#15]
Hi,
I tried to use your config for libinput gestures in both the local config ~/.config/libinput-gestures.conf and /etc/libinput-gestures.conf. Every time I change swipe up and down and execute libinput-gestures-setup restart, I still get natural scrolling. I've logged out and back in and it still doesn't change. I've also restarted and that didn't help. I'm unsure what I should do or if I should ask you or report this issue with libinput-gestures. Hope you can help, thanks.

**Comment by rolandguelle** [comment]
Hi Ceiphr,
is the issue solved? Is something in the tutorial missed?
Best Roland
