### ISSUE TITLE
Suspend wakeup graphics issue

### ISSUE THREAD

**Issue by samr28** [rolandguelle/razer-blade-stealth-linux#16]
When I wake my system from the suspend state, it will occasionally flicker the screen and then either go black or display the lock screen. It won't let me move my mouse or anything so I just need to restart by holding the power button for a few seconds. I would guess that it's something related to the graphics driver. Has anyone run into a similar issue?

KDE Neon 5.12 (Ubuntu 16.04) installed on my 2017 Blade Stealth (7500U)

**Comment by rolandguelle** [comment]
Have you tried https://github.com/rolandguelle/razer-blade-stealth-linux#screen-flickering ?

**Comment by samr28** [comment]
No but I'll try it and report back if it solves my issue. It seems to occur at random so I won't know if it worked immediately.

Did you have any other more noticeable issues that were solved by this kernel param?

**Comment by rolandguelle** [comment]
Not tried, I've a 2016 RBS (currently with 18.04).

**Comment by rolandguelle** [comment]
maybe you should try "intel_idle.max_cstate=4" or "i915.edp_vswing=2", see #18 and #7

**Comment by rolandguelle** [comment]
would be great if you could confirm:
- https://github.com/rolandguelle/razer-blade-stealth-linux#screen-flickering
as a solution.
