### ISSUE TITLE
External monitor randomly going blank for a few seconds

### ISSUE THREAD

**Issue by emanuelet** [rolandguelle/razer-blade-stealth-linux#18]
Hi,
I'm experiencing some issues with the external monitor that I have hooked up to the HDMI port of my Razer Blade Stealth late '17 (CPU i7-8550 / Graphics Intel® UHD Graphics 620) with Ubuntu 18.04. Basically every once in a while the external screen goes blank for a few seconds. It looks pretty random in terms of frequency and delay, but another hypothesis that I have is that is connected with some particular draw commands that are being issued by the graphics card (because the problem normally always happen after an action on my side).
I already set the kernel parameter `i915.edp_vswing=2` but that didn't fix the problem.

If you have any ideas, please help.

Cheers

**Comment by rolandguelle** [comment]
Could you try: intel_idle.max_cstate=4  as kernel parameter? see #7

**Comment by rolandguelle** [comment]
Thanks for your feedback.
Have you tried Xorg and Wayland?

**Comment by emanuelet** [comment]
I'm on Xorg right now. Don't think that Wayland could work better

**Comment by emanuelet** [comment]
Can you think of anything else that could cause this?

**Comment by swarog** [comment]
Hello to all. The same issue with Blade Stealth late '17, Ubuntu 18.04 and external Samsung 4k monitor. Any ideas?

**Comment by emanuelet** [comment]
I can add that the problem happens with different monitors, as I tested a few

**Comment by benjob** [comment]
Just in case it helps, I can also confirm the flickering on the external display (connected through HDMI). I had the problem on both ubuntu 16.04.4 and 18.04 on 2 different razer blade stealth 8550u. I also tried different monitors and they all have the same problem. I tried both Xorg and Wayland and it flickers on both. I do not have any flickering on an external monitor connected to the USB-C port.
On windows, I have no flickering at all.

**Comment by brendanrankin** [comment]
Adding my $0.02 here as well. I experience the flickering (HDMI port ONLY) when using Chrome and/or watching videos in Firefox. If you use Firefox without videos or "active graphics" (something that would require rendering), no flickering.

No solution. And here I thought I'd be "safe" going with i915. <:‑| The state of the i915 driver(s) is a hot mess in Linux...particularly with anything high resolution.

**Comment by benjob** [comment]
@brendanrankin I don't know about the others but I am grateful for this! You are right, if I choose the "HDMI / DisplayPort - Built in Audio" it looks like the flickering goes away. If I connect headphones to the jack on the laptop then the flickering goes away too.
Also, it looks like when the monitor is "glitched", I can tell prior to any flickering happening by opening a black window on the desktop (usually a terminal) and move it around the screen. If I see a bunch of white dots on the screen while I move the window then the flickering will happen. If I don't see any white dot, no flickering. I confirm that with your workaround, I do not see any white dot. I have been using it for a couple of hours now and still haven't had any flicker. This has improved my user experience with this laptop on linux quite a bit. Thanks much!

**Comment by rolandguelle** [comment]
Thanks for this feedback!
Sounds that the issue is a combination with the HDMI out and audio.
Could this someone confirm (changing the audio output channel)?
(btw: I've no problem with my 2016 RBS)

**Comment by rolandguelle** [comment]
Sounds like a workaround for the 2017 RBS:
Screen Flickering on with external monitor on HDMI
=> Change output channel to "HDMI / DisplayPort - Built in Audio"
Right?

**Comment by benjob** [comment]
Yes, changing the output channel to "HDMI / DisplayPort - Built in Audio" fixed it for me! At least for the past couple of hours. I can get back to you at the end of today to confirm.
Alternatively, connecting headphones to the stereo jack on the laptop also seems to fix the problem but I tested that briefly.

**Comment by brendanrankin** [comment]
It worked for me for hours the other night (Western Conference Finals). I just didn't correlate it with changing the output sound "channel" to anything but the default and/or plugging in a headset until yesterday.

Funky issue, but since HDMI (and DP) standards support audio and video over the same wires it "feels" like an audio/video channelization issue. I'll work to file this at freedesktop.org and/or see if it's already been filed.

**Comment by jasonkenneth** [comment]
Thank you! Plugging headphones in appears to have worked with me. I have Ubuntu 18.04 running on a Dell Precision 5520 connected to two 30" monitors via TB16. It was driving me nuts.

**Comment by sharabash** [comment]
YES, THANK YOU

**Comment by WhyNotHugo** [comment]
Is there any upstream issue, or anything alike to further address the root cause of this issue?
The workaround _seems_ to work, but I'd like to know if there's anything being done upstream about it to permanently fix the issue.

**Comment by stephbur** [comment]
Not sure if this the right place, but I also would like to add my experience.
I have a pc with Ubuntu 18.10, Intel® HD Graphics P630 (Kaby Lake GT2) and 2 external Eizo EV2750 monitors connected by DisplayPort. I still experience this glitches (quick restart of the monitor, takes about 2 seconds), especially after some supposedly more demanding actions, such as scrolling fast in a PDF, quickly changing applications or after a couple hits on the super key (app overview in GNOME). 
The latter is very much reproducible and only appears on the monitor that the mouse is on. 
Changing the audio sources does not solve the problem for me.

**Comment by alisianoi** [comment]
Here is a different setup that experiences the described issues (picture + sound coming from external monitor cut off for ~2 seconds approximately each 10 minites):

Arch Linux on a Lenovo Thinkpad E580, connected to a [Thinkpad USB 3.0 Pro docstation][2] over a USB-C port. The docstation itself is hooked to a single Ben-Q PD2700Q over a display port cable.

Arch Linux is running GNOME 3.30.2

Previously, the external speaker were hooked to the docstation. Hooking them up to the monitor itself and setting the "HDMI / DisplayPort - Built in Audio" did not affect the issue. The flicker still happens at approximately the same frequency (once per ten minutes) at seemingly random times.

The `journalctl -xe` does not have relevant logs, one flicker event happened to me at 12:58 -- 12:59 and the journal only had events from 12:56 related to network, here is a sample:

```
дек 23 12:53:14 loki audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-hostnamed comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
дек 23 12:53:14 loki kernel: audit: type=1130 audit(1545558794.410:81): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-hostnamed comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? termi>
дек 23 12:53:44 loki audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-hostnamed comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
дек 23 12:53:44 loki kernel: audit: type=1131 audit(1545558824.483:82): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-hostnamed comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? termi>
дек 23 12:56:19 loki NetworkManager[541]: <info>  [1545558979.6191] device (wlp5s0): set-hw-addr: set MAC address to D6:0E:DF:0D:87:8F (scanning)
дек 23 12:56:20 loki kernel: IPv6: ADDRCONF(NETDEV_UP): wlp5s0: link is not ready
дек 23 12:56:20 loki NetworkManager[541]: <info>  [1545558980.0942] device (wlp5s0): supplicant interface state: inactive -> disabled
дек 23 12:56:20 loki NetworkManager[541]: <info>  [1545558980.1313] device (wlp5s0): supplicant interface state: disabled -> inactive
дек 23 12:56:20 loki wpa_supplicant[711]: wlp5s0: Reject scan trigger since one is already pending

```

[2]: https://support.lenovo.com/nl/en/solutions/acc100184

**Comment by Nosferath** [comment]
I just had this problem and I fixed it by changing the monitor frequency from 60Hz to 59,94Hz. I hope this advice is useful for someone.

**Comment by sebenik** [comment]
Changing the monitor frequency didn't fixed it for me.

**Comment by Nosferath** [comment]
It was not a permanent fix for me. What really fixed the blinking was rebooting. It seems that some drivers got installed and it required rebooting.

**Comment by boris** [comment]
This is the only "permanent" fix that has worked for me: https://github.com/rolandguelle/razer-blade-stealth-linux/issues/18#issuecomment-412237608

**Comment by sebenik** [comment]
Switching to new and shorter HDMI cable worked for me.

**Comment by danmtripp** [comment]
This has been happening to me for the last 12 months - identical issues - whether Ubuntu 18.04, elementary Juno, Xubuntu 18.04, Ubuntu 18.10 and 19.04... tried the headphone thing, changing the frequency down a notch, disable sound output over displayport... still happens...  At my work desk : Dell Latitude E7250, Dell docking station, 2 x Dell DP 24" monitors...  using same laptop and similar / identical docking station at home, with dual monitors, it NEVER happens - however - only one of those monitors is DisplayPort, the other one is DVI only...  so it's something to do with DP / HDMI I guess...  it's darn annoying - sometimes the monitors will stay plank - I have to yank the DP cables out of the back of the docking station...  annoying yeah, but still better than using Windows...  it seems to happen more often when I'm playing music, but not always...

**Comment by brendanrankin** [comment]
> This has been happening to me for the last 12 months - identical issues - whether Ubuntu 18.04, elementary Juno, Xubuntu 18.04, Ubuntu 18.10 and 19.04..

I believe intel_idle.max_cstate=4 is your friend. There's more than one issue... Have a look at #7

**Comment by stealson** [comment]
The fix suggested in [comment 18](https://github.com/rolandguelle/razer-blade-stealth-linux/issues/18#issuecomment-412237608) worked for me as well. Thank you very much! That regulated my temperament in the home office during the Corona crisis. 
Note: You don't need to use headphones. For me a simple audio connection cable with no other device connected worked as well.

**Comment by akostadinov** [comment]
I think issue is with driver used. For a long time I had this issue but only now I decided to spend time to fix. So I found this [blog](https://hobo.house/2018/05/18/fix-for-intel-i915-gpu-freeze-on-recent-linux-kernels/).

What helped me was to switch to the i915 driver. I don't see any blackouts since 2 days.
```
🐚 cat /etc/X11/xorg.conf.d/10-intel.conf 
Section "Device"
Identifier "Intel Graphics"
Driver "intel"
EndSection
```
But I figured I can just delete the intel driver instead `xorg-x11-drv-intel`, then it will not be used. I have not tested with a restart yet, to make sure still i915 is used. But I read somewhere on the internet that removing it is a best practice.

-- Linux 5.6.11

**Comment by sgtnoodle** [comment]
This problem is happening to me too, on Ubuntu 20.04. Razer blade stealth 2017. The HDMI monitor blacks out every minute or two, and I have white pixel noise.

Setting audio to HDMI doesn't work, but plugging in headphones seems to do the trick.

```
server glx vendor string: SGI
client glx vendor string: Mesa Project and SGI
    Vendor: Intel (0x8086)
OpenGL vendor string: Intel
```

```
00:02.0 VGA compatible controller: Intel Corporation UHD Graphics 620 (rev 07)
```

I haven't tried a different HDMI cable yet. The cable works fine in windows 10 though.

**Comment by AlexOros** [comment]
Hey, @sgtnoodle Found a solution yet?. I have the exact issue on Ubuntu 20.04 Laptop-msi-prestige 15 A10SC-406XRO with a lg ultra had 27UL550. Image bouth monitors go black at random intervals and at some point it losses signal completely to the external lg monitor.

Plugging the headphones dose not work for me :(

**Comment by sgtnoodle** [comment]
Unfortunately, no. I did switch to a thunderbolt dock and its displayport
output is stable. The dock setup has plenty of its own reliability problems
though. They're either due to the dock (an expensive plugable brand one
that doesn't work well in windows either), or the laptop's thunderbolt
controller firmware.

This week, the only way I can reliably type is with a USB 1.1 external
keyboard. The built-in keyboard drops key presses when it hasn't been used
within a couple seconds, and modern keyboards with USB3 glitch out and
"stutter" keypresses every 10 seconds or so. The former is probably a
keyboard controller firmware power save issue, and the latter is the devil
trying to speak to me.

I could describe a dozen more maddening issues with the razer stealth that
plague me on a weekly basis. Some of them are probably bugs in 20.04 rather
than the laptop, but most of them are obviously hardware or firmware flaws
that plague windows too and it's enough to make me never recommend a razer
product to anyone. It's my work laptop, and I've lost enough productivity
over the last couple months to justify buying a new laptop that hopefully
can run Ubuntu longer than 6 hours between reboots...

**Comment by BenEngbers** [comment]
I have a thinkpad, t470s running Fedora 33 and using Gnome. The first time I attached an external monitor (Philips 276e), I manually changed display to use the external monitor. The screen went black so often that this was not workable so I decided to buy a docking station (Thinkpad USB-C Dock gen2).
When I plug in the USB-C, Fedora starts using the external dislay automatically. The screen still randomly goes black.
I also noticed that randomly the screen starts trembling from left to right during a few seconds.

Are the two problems related?

**Comment by BenEngbers** [comment]
I have a thinkpad, t470s running Fedora 33 and using Gnome. The first time I attached an external monitor (Philips 276e), I manually changed display to use the external monitor. The screen went black so often that this was not workable so I decided to buy a docking station (Thinkpad USB-C Dock gen2).
When I plug in the USB-C, Fedora starts using the external dislay automatically. The screen still randomly goes black.
I also noticed that randomly the screen starts trembling from left to right during a few seconds.

Are the two problems related?

**Comment by clockzhong** [comment]
Thanks all of you, I've fixed this issue also for me with the same solution:

Choose the output of the audio through external HDMI instead of the mother board autio output, then this externel HDMI output flash disappears. 

It seems the root cause is in the Linux audio&gfx driver, the current linux HDMI video output couldn't synch with motherboard internal audio output after sometime, then the HDMI video output will refresh one time to catch sync with the audio, if the audio could be bundled with HDMI video to output, this unsync issue could be avoided(it doensn't means the driver's bug fixed) . It seems the best solution in the current situation.

**Comment by BenEngbers** [comment]
Strange observation.

My movements while working seem to have influence on the frequency with which my screen goes black?

My monitor can display 3840*2160 and 2560*1440. 
When using 3840*2160, slight movements from my hand / touching the mouse already triggers a black screen.
When using 2560*1440, the screen is rather stable. But when I get up after having worked some time, chances are high that the screen goes black. if I move all the time, the screen keeps working.

**Comment by clockzhong** [comment]
Another solution is using mirror(two screen display same content), this choice also could help fix this issue in my situation.

**Comment by moefear85** [comment]
I had this problem too and it was driving me crazy... It kept happening on very specific actions, like pressing tab in the console. After reading this post, it hit me like a ton of bricks. I don't have any sound output capability, so I never realized the corrolation between the actions and system sounds...

So I connected a bluetooth headset to reroute the sounds. It immediately resolved the issue!! Yeah, you don't even need a cable!

**Comment by ashersilver** [comment]
> Solved: Changed Cable:   I had a long (20"), old HDMI cable and started experiencing it when I changed from a HD monitor to 190x1080 to  3440 × 1440.  Changing to a newer (HDMI 2.1), shorter Cable solved it for me immediately.  A clue was that if I opened any window larger than approx 1/3 of the monitor the blackouts happened until I resized or closed the offending window. On Ubuntu 20.04

**Comment by AndyBarcia** [comment]
Isn't there a permanent normal solution to this problem that doesn't involve changing the audio output? I mean, this thread is so old, surely there must have been an update to fix this problem by now?
