### ISSUE TITLE
RBS touchpad deadzone fix was merged into 4.17

### ISSUE THREAD

**Issue by collarchoke** [rolandguelle/razer-blade-stealth-linux#19]
The touchpad deadzones issues for late 2017 RBS have been addressed in: https://bugs.freedesktop.org/attachment.cgi?id=138113 , which has been merged into the current 4.17 RC. So when 4.17 hits stable, we should see a fully functional touchpad for the RBS.

**Comment by rolandguelle** [comment]
Thanks for this info!

**Comment by rolandguelle** [comment]
I try the 4.17.0-rc7 kernel, but I see not really a better result. Have you tried it?

**Comment by collarchoke** [comment]
I have not, just saw the patch going in and the thread describing that it was supposed to address the deadzone, was waiting for 4.17 to go stable, but if the supposed fix is not functional that sucks.

**Comment by collarchoke** [comment]
Also relevant (not in a mainline systemd release yet): https://github.com/systemd/systemd/pull/8436

**Comment by emanuelet** [comment]
I just installed 4.17.1 and I can say from a quick try that the touchpad is working way better now
