### ISSUE TITLE
Hide mouse cursor when using touch screen?

### ISSUE THREAD

**Issue by schultzern** [rolandguelle/razer-blade-stealth-linux#2]
Hi, 

I was wondering if you by any chance have found a way to hide the cursor when interacting with the touch screen? I find it annoying that the mouse follows my fingers...

**Comment by rolandguelle** [comment]
I don't have this issue on Gnome at Wayland or X11, Ubuntu 17.04 or Arch / Antergos.
Maybe a Window Manager / Env problem?
