### ISSUE TITLE
Crash when unplugging keyboards from 2017 Razer Blade Stealth

### ISSUE THREAD

**Issue by jellybob** [rolandguelle/razer-blade-stealth-linux#20]
I know this isn't read by the actual Razer team, but it does seem like the best place to collect Linux annoyances with these laptops. (And thanks for all the effort, after reinstalling and running through the config here for the first time ever my laptop mostly works properly!)

I'm getting the same behaviour when unplugging a keyboard as I see when toggling caps lock, namely static on the audio output and display, and a hard crash. I assume this is something to do with the system caps lock state attempt to resolve itself to the currently connected input devices, but I have no idea if its possible to disable that behaviour.

**Comment by rolandguelle** [comment]
Never tried an external keyboard, but I'll try.
Does https://github.com/rolandguelle/razer-blade-stealth-linux#disable-capslocks helps?

If not,  check this workaround:
https://github.com/rolandguelle/razer-blade-stealth-linux#x11-disable-built-in-keyboard-driver

Check with `xinput` the keyboards before plugin and after.
If there are multiple keyboards added, disable the _RAW_ variant (same as the workaround):
```
xinput set-prop "AT Raw Set 2 keyboard" "Device Enabled" 0
```
(Replace "AT Raw Set 2 keyboard" with the multiple external one)

**Comment by jellybob** [comment]
I've already changed the config to stop caps lock being toggled. Curiously this seems to have stopped happening recently, although I have no idea why since I haven't actually changed anything since opening this ticket. I'm going to close it.
