### ISSUE TITLE
RBS 2017 Webcam

### ISSUE THREAD

**Issue by lecler-i** [rolandguelle/razer-blade-stealth-linux#21]
Hello there, thanks for all the good work and detailed guide !

I have a RBS 2017 and everything is working but the webcam, all we all know.

But i noticed it works almost perfectly (at least it's not all green or black and have decent fps) using Slack or Hangout ! 
it's the only two website i figured it is working (even betetr than using a software).

I know nothing about codecs and webcam in general, but why is this so ? 
Would it be possible to use the same stream as they use on slack/hangout and create a "virtual webcam" from this good stream, to be able to use it on any other software / websites?

Sorry about this issue, it's not really an issue about the repo but more a question and some "ask for help" arround webcam workarround

**Comment by rolandguelle** [comment]
Do you used Slack and Google Hangout in your browser?
Chromium, Firefox or Chrome?

**Comment by rolandguelle** [comment]
I've tried https://www.cam-recorder.com/, works very slow.
Cheese works with 176x144.

**Comment by rolandguelle** [comment]
The webcam issue is still open with 18.10, I put the browser / webview info in the unsolved issue / webcam section.

**Comment by parkerlreed** [comment]
You can see the same thing just using any webcam viewer.

If I bump it up to 1080 in guvcview, I get the distorted image (Stealth late 2016 i7-7500U)

![image](https://user-images.githubusercontent.com/841440/47319774-96f78680-d61d-11e8-9c80-70b2fdfd9dbd.png)

![image](https://user-images.githubusercontent.com/841440/47319818-ad054700-d61d-11e8-9d54-f674e66427b3.png)

![image](https://user-images.githubusercontent.com/841440/47319847-c4dccb00-d61d-11e8-9cf0-9301b18ae806.png)

Even 720 isn't guaranteed 

![image](https://user-images.githubusercontent.com/841440/47319896-dfaf3f80-d61d-11e8-8d06-79f86a5a8358.png)

**Comment by parkerlreed** [comment]
Any word on this? Still happening. And I don't see anywhere that has any possible explanation why.

**Comment by GuilhermeBarile** [comment]
After quite some time I found a fix for this (it could live with that because it worked with Zoom, but recently after a kernel upgrade artifacts started appearing there too).

I added

```
options uvcvideo nodrop=1
```

To /etc/modprobe.d/uvcvideo.conf

And reloaded the driver with `rmmod uvcvideo`, `modprobe uvcvideo`

To my surprise, even Cheese works now

**Comment by bretello** [comment]
Adding `quirks=512` might also slightly improve webcam quality: https://wiki.archlinux.org/title/Razer_Blade#Webcam_2
