### ISSUE TITLE
Just a heads up, touchpad is fixed.

### ISSUE THREAD

**Issue by ZVNexus** [rolandguelle/razer-blade-stealth-linux#24]
In latest kernel (4.18 rc3) the touchpad fix isn't required. Works without issue now out of box.

**Comment by rolandguelle** [comment]
Thanks! Tested on what model & distro?

**Comment by ZVNexus** [comment]
@rolandguelle I tested it on the i7 6500u model, on both Ubuntu 18.04 and 18.10 (daily build).

**Comment by luisgarciaalanis** [comment]
great to hear this. 
Can you have your thumb touching the button and still move the mouse pointer using another finger?

**Comment by rolandguelle** [comment]
> @rolandguelle Just an update, because 18.10 will be shipping with 4.18 by default this means the touchpad is no longer an issue, by default. :)

Confirmed with a quick check on 18.10 beta with Wayland.
I'll recheck this when 18.10 official released with all workarounds and tweaks.

**Comment by rolandguelle** [comment]
I'll update the tutorial when 18.10 is official released.
I'm running 18.10 for 2 days without (touchpad) problems and libinput.
