### ISSUE TITLE
bumblebee kills external monitor

### ISSUE THREAD

**Issue by OptogeneticsandNeuralEngineeringCore** [rolandguelle/razer-blade-stealth-linux#25]
Super awesome repo! Thanks.

But I did a bunch of these and then did a reboot and lost my external monitor (black screen). It wouldn't even show up in Display. I tried all day to update drivers and chased several versions of nvidia, no version (purge nvidia), and lots of others. Eventually I used Timeshift to push back to a state before I did anything from this repo and chased the issue down to bumblebee. This command is what kills the external monitor (hdmi):

$ sudo apt-get install bumblebee bumblebee-nvidia primus linux-headers-generic

after a reboot. Probably an issue with bumblebee, but thought I would post here for others. I will update if I ever find the time to chase this.

Linux Mint 19
Razer Blade late 2016
GTX 1060
1080p

**Comment by rolandguelle** [comment]
The tutorial is tested with the Razer Blade **Stealth**, the bumblebee configuration (broken in 18.04.) is for the Razer Core with an external GPU :)
The Razer Blade don't need bumblebee, the Nvidia card is the primary GPU.

The (bumblebee) installation blacklists lot of nvidia modules, so check /etc/modprobe.d/

**Comment by rolandguelle** [comment]
Please reopen this issue, if there is feedback.
