### ISSUE TITLE
Ubuntu 18.04 has problems resuming from suspend

### ISSUE THREAD

**Issue by jheise** [rolandguelle/razer-blade-stealth-linux#27]
In the past week my 2016 RBS running Ubuntu 18.04 has started having issues with resuming from suspend, it seems like it will resume once after i shut the lid, but if i shut the lid a second time the system seems to freeze, either with a black screen or a frozen unlock screen.

**Comment by imtan** [comment]
I used 2018 RBS running Xubuntu 18.04. I had same issue.
 May be you  fix `IgnoreLid=true` to `IgnoreLid=false` in `/etc/UPower/Upower.conf`

**Comment by rolandguelle** [comment]
Have you tried https://github.com/rolandguelle/razer-blade-stealth-linux#suspend-loop
Is your 18.04 a fresh install or an update?

**Comment by jheise** [comment]
Just reinstalled again after replacing the hard drive, now i'm seeing the suspend loop

**Comment by rolandguelle** [comment]
Could you check the logfiles when the system hangs?
Could you try to disable WIFI before suspend?
