### ISSUE TITLE
Recent battery issues with 18.04

### ISSUE THREAD

**Issue by samr28** [rolandguelle/razer-blade-stealth-linux#29]
Just updated my blade stealth (2017) to 18.04 and have been only been getting 3 hours of battery. I think it might have something to do with the fans as they seem to be louder than before. I'm not sure if this is actually what's causing the battery issues though.

I've been monitoring cpu and ram usage which seems to be averaging around 28% CPU and 4.5GB/16GB ram. Seems pretty normal to me.

Is anyone else running into this issue?

Ubuntu 18.04 (4.18.0-3-generic)

**Comment by rolandguelle** [comment]
18.04 runs without problems for a while (currently I'm running 18.10 beta).
What process eats your CPU and RAM?

**Comment by samr28** [comment]
ksysguard is showing that ssdm-greeter is using 25% cpu :O 

I bet this is related to my xserver issues

**Comment by rolandguelle** [comment]
`journalctl -u display-manager` or  `less /var/log/Xorg.log`

maybe reset (backup before!) your ssdm.conf
`sddm --example-config > /etc/sddm.conf`

**Comment by rolandguelle** [comment]
I guess more a local configuration / upgrade problem - not a general system / hardware issue.
If this issue still exists with a clean 18.10 installation, please reopen it.
