### ISSUE TITLE
Crash after Signup

### ISSUE THREAD

**Issue by TheLucasSchwarz** [rolandguelle/razer-blade-stealth-linux#42]
Hello, i installed Ubuntu 18.04 on RBS 2016 7500U with UHD-Display.
Most time i started the device, it boots up to the Signup. But most times after the Signups, the System crashs with grizzling sounds and weird artifacts on the screen. Then i can only shut down the device with the power button. Only a few times, the system works. But then it works fine. Help me please.

**Comment by Earthquake125** [comment]
Same issue on my RGB 2016 7500U on every distro I've tried.

**Comment by rolandguelle** [comment]
Have you tried this fix?
https://github.com/rolandguelle/razer-blade-stealth-linux/blob/master/ubuntu-21-04.md#caps-lock-crash

**Comment by Earthquake125** [comment]
My issue ended up being an improperly configured driver. I'm not sure about luxn1997 though.
