### ISSUE TITLE
Suspend wake issue

### ISSUE THREAD

**Issue by bretello** [rolandguelle/razer-blade-stealth-linux#43]
Hello, I've been having problems with a Razer Blade Stealth 2017 (I7-8550U) immediately waking up from suspend: led indicator goes white for half a second, then turns green and the laptop immediately wakes up again.

I'm running Manjaro with gnome, but the issue is also reproducible on an archlinux iso and an ubuntu live.

I tried the following:
- adding `button.lid_init_state=open` to kernel cmdline options
- `echo XHC | sudo tee /proc/acpi/wakeup`
- Set `IgnoreLid=true` in `/etc/UPower/UPower.conf`
- Set `HandleLidSwitch=ignore` in `/etc/systemd/logind.conf` (and other lid-related options)
- Disabled "Suspend when laptop lid is closed` in `gnome-tweaks`

I noticed that the acpi lid state is stuck on "closed" (it's set on "open" on boot, but gets stuck on closed after the first suspend)
    
> $ cat /proc/acpi/button/lid/LID0/state
> state:      closed

What I see by monitoring acpi events with `acpid` and `acpi_listen`, is that after each suspend event I get the following entries in the logs (even if I don't open/close the lid):
> button/lid LID close
> button/lid LID open

I'm not sure this is helpful and/or wrong behaviour

The issue is particularly weird because the issue disappears when connected to a USB-C hub (power passthrough/hdmi/USB) connected to an external monitor and keyboard/mouse, the laptop suspends and does not wake up, not even when unplugged.

**Comment by bretello** [comment]
Sleep works just fine when `boltd` is running.

**Comment by bretello** [comment]
Ended up setting up a script that gets called after suspend: `/lib/systemd/system-sleep/fix_sleep_after_hibernation`, it probably would be better to write it as a systemd unit, but this hack seems to be working well enough. Check out `man systemd-sleep` for more information

```bash
#!/bin/sh

# Restarts boltctl so that the Razer Blade Stealth 2017 (i7-8550U) does not
# immediately wake from suspend when suspending after an hibernation

if [[ $1 == "post" ]]; then
    if [[ $2 == "hibernate" || $2 == "suspend-then-hibernate" || $2 == "hybrid-sleep" ]]; then
        # Restarting bolt seems to fix instant wakes after suspend.
        # This issue seems to be triggered when the system is hibernated
        systemctl restart bolt
        # Acquire power for 1 second, this seems fix system not suspending
        # when closing the lid after hibernation
        boltctl power -t 1
    fi
fi


logger "$0 called with args: $1 $2"
```

**Comment by rolandguelle** [comment]
Thanks, should we add this? If you like, create a merge request or assign this task to me.
