### ISSUE TITLE
Black Screen on external monitor connected to the Core

### ISSUE THREAD

**Issue by raflopjr** [rolandguelle/razer-blade-stealth-linux#8]
Not sure if this is the appropriate place to post this, but I followed the instructions and razercore status confirms that it is connected, however the monitor connected to my gtx1060 in the core shows that it has a signal since the display stays on except that it is black. I am unsure if I missed a step to enable the display or if it may just be a bug, any help would be greatly appreciated!

Not sure if it helps but I am running a Intel 6500u (Skylake) Razer Blade stealth with a V1 Razer Core and an EVGA GTX1060 6GB on Ubuntu 17.10

**Comment by rolandguelle** [comment]
Works the core with your laptop / internal display?
What video output do you use?

**Comment by raflopjr** [comment]
I actually got it sort of working, I had to use the log in with Xorg to get it to work, except plug in play is no longer working, If I unplug, Ubuntu pretends like the other device is still connected. So I guess Wayland isn't working for me. And Xorg is sort of working. (I think Xorg and X11 are the same? I'm a noob)
 

BTW thanks so much for this awesome repo, a true hero.

**Comment by raflopjr** [comment]
Internal Display works on Wayland, but I can't actually start nvidia-settings on Wayland to swap to the Nvidia gpu.

**Comment by rolandguelle** [comment]
The nvidia-settings are not needed. The setup runs the external GPU as a discrete card. With optirun / primusrun you run an application at your external GPU.

For a (possible - not tested) working nvidia-settings, run 
`prime-select nvidia`

**Comment by raflopjr** [comment]
Would this configuration work for using the core to extend my desktop to use a multi monitor setup or only run a specific app on it?

**Comment by rolandguelle** [comment]
Yes, the setup is (currently) only tested for run an application on the external GPU.

**Comment by rolandguelle** [comment]
I played with an external screen connected with the Razer Core and extended "razercore" and the tutorial:
https://github.com/rolandguelle/razer-blade-stealth-linux#external-display
Still WIP and needs some testing, but a start :)
